### ISSUE TITLE
Test Angular.js in Chrome Extension

### ISSUE THREAD

**Issue by cesine** [cesine/todomvc-for-chrome-extensions#4]
Status:  works

Added an external css file and now the {{variableNames}} are not visible

``` css
[ng-cloak] {
    display: none
}
```

Added a directive in the html tag to turn off eval

``` html
<html lang="en" ng-app="todomvc" ng-csp="">
```
